# Generated by Django 5.0.6 on 2024-09-04 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_student_email_alter_student_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='PRN',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
