# Generated by Django 5.0.6 on 2024-09-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_student_prn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='ALT_Mobile_NO',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='MOBILE_NO',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='PRN',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
