# Generated by Django 5.0.6 on 2024-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0024_alter_activity_options_activity_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='booklets',
            options={},
        ),
        migrations.AlterModelOptions(
            name='drive',
            options={},
        ),
        migrations.AlterField(
            model_name='activity',
            name='Reference_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='industry_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='booklet',
            field=models.FileField(null=True, upload_to='booklets/'),
        ),
        migrations.AlterField(
            model_name='booklets',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='Bond',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='Reference_no',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='application_last_date',
            field=models.DateField(default='2002-12-02', null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='company_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='drive_status',
            field=models.CharField(choices=[('Closed', 'Closed'), ('Active', 'Active'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='industry_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_CTC',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_eligibility',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='job_role',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='num_rounds',
            field=models.IntegerField(default=1, null=True, verbose_name='Number of Rounds'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='resume_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
